###
# ```{rubric} API Version
# ```
# ---
# The Helm API version to use for this chart.
#
# ```{literalinclude} /deployment/helm/k8s-agent/Chart.yaml
# :language: yaml
# :start-at: "apiVersion: v2\n"
# :end-before: "###\n"
# ```
apiVersion: v2

###
# ```{rubric} App Version
# ```
# ---
# This is the version number of the application being deployed.
# This version number should be incremented each time you make changes to the
# application. Versions are not expected to follow Semantic Versioning.
#
# They should reflect the version the application is using.
#
# It is recommended to use it with quotes.
#
# ```{literalinclude} /deployment/helm/k8s-agent/Chart.yaml
# :language: yaml
# :start-at: "appVersion: \"0.0.1\"\n"
# :end-before: "###\n"
# ```
appVersion: "0.0.1"

###
# ```{rubric} Description
# ```
# ---
# A brief description of the Chart.
#
# ```{literalinclude} /deployment/helm/k8s-agent/Chart.yaml
# :language: yaml
# :start-at: "description: The Kubernetes Operator Agent is a simple agent for operating LLMs.\n"
# :end-before: "###\n"
# ```
description: The Kubernetes Operator Agent is a simple agent for operating LLMs.

dependencies:
- name: redis-stack-server
  version: ">=0.4.8"
  repository: https://redis-stack.github.io/helm-redis-stack/

###
# ```{rubric} Icon
# ```
# ---
# A url or file path to an icon for the Chart's application.
#
# ```{literalinclude} /deployment/helm/k8s-agent/Chart.yaml
# :language: yaml
# :start-at: "icon: file://./_static/img/logo/k8s-operator-agent.jpg\n"
# :end-before: "###\n"
# ```
icon: file://./_static/img/logo/k8s-operator-agent.jpg

###
# ```{rubric} Name
# ```
# ---
# The name of the application or library provided by the chart.
#
# ```{literalinclude} /deployment/helm/k8s-agent/Chart.yaml
# :language: yaml
# :start-at: "name: k8s-agent\n"
# :end-before: "###\n"
# ```
name: k8s-agent

###
# ```{rubric} Type
# ```
# ---
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
#
# ```{literalinclude} /deployment/helm/k8s-agent/Chart.yaml
# :language: yaml
# :start-at: "type: application\n"
# :end-before: "###\n"
# ```
type: application

###
# ```{rubric} Version
# ```
# ---
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
#
# ```{literalinclude} /deployment/helm/k8s-agent/Chart.yaml
# :language: yaml
# :start-at: "version: 0.0.1\n"
# ``
version: 0.0.1
