###
# ```{rubric} Deploy Documentation
# ```
# ---
# GitHub Actions configuration to deploy pages.
#
# ```{literalinclude} ../.github/workflows/docs.yml
# :language: yaml
# :caption: .github/workflows/docs.yml#name
# :start-at: "name: Deploy Documentation\n"
# :end-before: "###\n"
# ```
name: Deploy Documentation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
    contents: read
    issues: read
    checks: write
    pull-requests: write
###
# ```{rubric} Jobs
# ```
# ---
# Define jobs to deploy to pages.
#
# ```{literalinclude} ../.github/workflows/docs.yml
# :caption: .github/workflows/docs.yml#jobs
# :language: yaml
# :start-at: "jobs:\n"
# :end-before: "  ###\n"
# ```
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.11
          cache: pipenv
      - name: Setup pages
        uses: actions/configure-pages@main
      - name: Build the site
        run: |
          set -x
          cd docs
          pip install -U pip pipenv
          pipenv install
          pipenv run sphinx-build . ./deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: './docs/deploy'
  ###
  # ```{rubric} Deploy to pages
  # ```
  # ---
  # Download the artifact and deploy to pages.
  #
  # ```{literalinclude} ../.github/workflows/docs.yml
  # :caption: .github/workflows/docs.yml#jobs.pages
  # :language: yaml
  # :start-at: "  pages:\n"
  # ```
  pages:
    needs: build
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download pages artifact
        id: download
        uses: actions/download-artifact@main
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
